In [1]:
#1.
import numpy as np

In [2]:
#2.
np.__version__

'1.21.2'

In [3]:
np.show_config

<function numpy.__config__.show()>

In [16]:
#3.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#4.
array1 = np.array([1, 2, 3, 4, 8])

array1.size*array1.itemsize

40

In [80]:
#5.
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [17]:
#6.
zeros = np.zeros(10)
zeros[4] = 1

print(zeros)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [126]:
#7.
vector1 = np.arange(10, 50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [24]:
#8.
vector1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [118]:
#9.
matrix1 = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
np.reshape(matrix1, 9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
#10.
array2 = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(array2)

(array([0, 1, 4]),)

In [33]:
#11.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
#12.
np.random.random((3, 3, 3))

array([[[0.81459846, 0.49898901, 0.33231072],
        [0.8085028 , 0.57015217, 0.76578794],
        [0.54143874, 0.32991915, 0.85666707]],

       [[0.17965282, 0.49610868, 0.19395457],
        [0.60486575, 0.57791472, 0.23998663],
        [0.47862131, 0.28848602, 0.67246807]],

       [[0.75020317, 0.34058482, 0.06031559],
        [0.71773796, 0.97778451, 0.98711356],
        [0.17276227, 0.60733369, 0.0480171 ]]])

In [65]:
#13.
random_matrix = np.random.random((10, 10))
print(random_matrix.min())
print(random_matrix.max())

0.004057365417018732
0.9975911320738257


In [66]:
#14.
random_vector = np.random.rand(30)
print(random_vector)
np.mean(random_vector)

[0.93623707 0.41538027 0.39798851 0.87211774 0.00566361 0.85473231
 0.61968982 0.72680945 0.39395913 0.29738335 0.22079648 0.12723544
 0.50303305 0.63828024 0.28675603 0.47493253 0.65559399 0.6423621
 0.2326669  0.74883746 0.60381243 0.75291863 0.88044983 0.51363515
 0.46286627 0.33222403 0.68886218 0.02877156 0.68836515 0.38741821]


0.5129926311999358

In [74]:
#15.
array3 = np.ones((8))
array3[1:-1] = 0
print(array3)

[1. 0. 0. 0. 0. 0. 0. 1.]


In [79]:
#40.
random_vector2 = np.random.rand(10)
print(np.sort(random_vector2))

[0.05470827 0.24570228 0.46049244 0.48200754 0.52996217 0.63412516
 0.64919655 0.84589268 0.96663093 0.97978168]


In [81]:
#41.
np.add.reduce(array3)

2.0

In [82]:
#42.
np.array_equal(array1, array2)

False

In [87]:
#43.
array1.setflags(False)
array1.flags.writeable

False

In [91]:
#44.
cart_matrix = np.random.random((10, 2))
print(cart_matrix)

x = cart_matrix[:, 0]
y = cart_matrix[:, 1]

print(np.sqrt(x**2+y**2))
print(np.arctan2(y, x))

[[0.01719718 0.66010003]
 [0.1139947  0.53443186]
 [0.55471707 0.51832786]
 [0.54358655 0.84567157]
 [0.78881072 0.39398084]
 [0.60388314 0.68608214]
 [0.81093897 0.72855898]
 [0.2164976  0.34966274]
 [0.78008105 0.95513025]
 [0.80473381 0.57654727]]
[0.660324   0.54645421 0.75919352 1.00530927 0.88172742 0.91399319
 1.09014687 0.41126056 1.23320729 0.98995114]
[1.54474984 1.36064493 0.75149906 0.9995086  0.46321697 0.84903399
 0.73193821 1.01640673 0.88593865 0.62167763]


In [96]:
#45.
rand_vec = np.random.random(10)
print(np.argmax(rand_vec))
rand_vec[4] = 0
print(rand_vec)

1
[0.56598175 0.90165424 0.08855143 0.07927174 0.         0.86176696
 0.29749914 0.24093026 0.83666164 0.23077577]


In [97]:
#46.
xvalues = np.array([0, 1])
yvalues = np.array([0, 1])

print(np.meshgrid(xvalues, yvalues))


[array([[0, 1],
       [0, 1]]), array([[0, 0],
       [1, 1]])]


In [100]:
#48.
print(np.iinfo(np.int16).min)
print(np.iinfo(np.int16).max)

-32768
32767


In [112]:
#49.
np.set_printoptions(threshold=np.inf)
print(random_vector2)

[0.05 0.97 0.25 0.63 0.53 0.85 0.65 0.48 0.98 0.46]


In [113]:
#50.
array4 = np.arange(50)
scalar = 6.8

new_array = np.abs(array4-scalar)
print(new_array.argmin())

7


In [124]:
#72.
ordered_array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
ordered_array[[0, 2]] = ordered_array[[2, 0]]
print(ordered_array)

[[6 7 8]
 [3 4 5]
 [0 1 2]]
